# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(verbose_name='a name that will appear in the admin')),
                ('loudness', models.IntegerField()),
                ('animals_it_eats', models.ManyToManyField(related_name='_cat_animals_it_eats_+', related_query_name='eaten_by', to='zoo.Cat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(verbose_name='a name that will appear in the admin')),
                ('barks', models.BooleanField(default=True)),
                ('animals_it_eats', models.ManyToManyField(related_name='_dog_animals_it_eats_+', related_query_name='eaten_by', to='zoo.Dog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Genus'),
        ),
        migrations.AddField(
            model_name='cat',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Genus'),
        ),
        migrations.CreateModel(
            name='BigCat',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('zoo.cat',),
        ),
        migrations.AlterUniqueTogether(
            name='dog',
            unique_together=set([('name', 'genus')]),
        ),
        migrations.AlterUniqueTogether(
            name='cat',
            unique_together=set([('name', 'genus')]),
        ),
    ]
